dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - gcc-5
      - g++-5

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.3.1/bazel_0.3.1-linux-x86_64.deb
  - sha256sum -c conf/bazel_0.3.1-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.3.1-linux-x86_64.deb

script:
  - export CC=gcc-5 && bazel test //src:all
